### ISSUE TITLE
Live demo for portfolio.

### ISSUE THREAD

**Issue by aakbarkhan** [aakbarkhan/Portfolio#6]
I have already made the project live so I create an issue and submit the link for the project.
https://aakbarkhan.github.io/Portfolio/

**Comment by carlos-ssh** [comment]
Hi @aakbarkhan , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that CREATE A PULL REQUEST AND RUN LINTERS.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by aakbarkhan** [comment]
Hi, May I used it this way. 
If by any chance you have deployed your app earlier, submit a link to your README file with a link to the online version of your app.

**Comment by aakbarkhan** [comment]
Invalid Code Review Request
